name: cached_video_player
description: A new flutter plugin that is virtually a clone of official video_player plugin except that it supports caching( Android and iOS)
version: 2.0.4
publish_to: none
homepage: https://github.com/vikram25897/flutter_cached_video_player

flutter:
  plugin:
    platforms:
      android:
        package: com.lazyarts.vikram.cached_video_player
        pluginClass: CachedVideoPlayerPlugin
      ios:
        pluginClass: CachedVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  meta: ^1.9.1
  video_player_platform_interface:
    git: https://github.com/kumsumit/video_player_platform_interface.git

  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint. The exact value doesn't matter since
  # the constraints on the interface pins it.
  # TODO(amirh): Revisit this (either update this part in the design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  video_player_web:
    git: https://github.com/kumsumit/video_player_web.git

  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: 
    git: https://github.com/kumsumit/flutter_lints.git
  pigeon:
    git: https://github.com/kumsumit/pigeon.git

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

